name: Deploy to EC2

on:
  push:
    branches:
      - main  # 每次推送到 main 分支時觸發

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      env:
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
        ssh -i ~/.ssh/deploy_key $EC2_USER@$EC2_HOST "
          cd ~/simpleweb &&
          git pull origin main &&

          # 後端啟動
          pm2 start server.js --name backend || pm2 restart backend &&

          # 進入前端目錄並構建
          cd frontend &&
          npm install &&
          npm run build &&

          # 啟動前端應用
          pm2 serve dist 3001 --name frontend || pm2 restart frontend
        "
    # - name: Update MongoDB with JSON data
    #   env:
    #     MONGODB_URI: ${{ secrets.MONGODB_URI }}
    #   run: |
    #     python -m pip install pymongo # 安裝pymongo
    #     python update_mongodb.py      # 執行更新腳本
    
    # - name: Save log file to EC2
    #   env:
    #     EC2_USER: ${{ secrets.EC2_USER }}
    #     EC2_HOST: ${{ secrets.EC2_HOST }}
    #   run: |
    #     scp -i ~/.ssh/deploy_key data_insertion.log $EC2_USER@$EC2_HOST:/home/ec2-user/simpleweb/logs/