name: Deploy to EC2

on:
  push:
    branches:
      - main  # 每次推送到 main 分支時觸發

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts
    
    - name: Create .env file on EC2
      env:
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        MONGODB_URI: ${{ secrets.MONGODB_URIATEC2 }}
        PUBLICIP: ${{ secrets.PUBLICIP }}
      run: |
        ssh -i ~/.ssh/deploy_key $EC2_USER@$EC2_HOST "
          echo 'REACT_APP_PUBLIC_IP=${PUBLICIP}' > ~/simpleweb/frontend/.env
          echo 'MONGODB_URI=${MONGODB_URI}' > ~/simpleweb/.env &&
          echo 'PORT=3000' >> ~/simpleweb/.env &&
          echo 'PUBLICIP=${PUBLICIP}' >> ~/simpleweb/.env
        "
    # - name: Build React App with PUBLICIP
    #   run: |
    #     echo "REACT_APP_PUBLIC_IP=${{ secrets.PUBLICIP }}" >> ~/simpleweb/frontend/.env.local &&
    #     cd ~/simpleweb/frontend &&
    #     npm install &&
    #     num run build

    - name: Deploy to EC2
      env:
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
        ssh -i ~/.ssh/deploy_key $EC2_USER@$EC2_HOST "
          cd ~/simpleweb &&
          git reset --hard HEAD &&  # 清除所有本地變更
          git pull origin main &&

          # 後端啟動
          pm2 start server.js --name backend || pm2 restart backend &&

          # 啟動前端應用
          cd frontend &&
          rm -rf dist &&  # 清除舊的靜態文件
          npm install &&
          npm run build &&

          # 重新啟動前端服務
          pm2 delete frontend || true &&
          pm2 serve dist 3001 --name frontend
        "
    # - name: Delete all data from MongoDB
    #   env:
    #     MONGODB_URI: ${{ secrets.MONGODB_URI }}
    #   run: |
    #     python -m pip install pymongo #安裝 pymongo
    #     python delete_all_data.py
    
    # - name: Save delete log file to EC2
    #   env:
    #     EC2_USER: ${{ secrets.EC2_USER }}
    #     EC2_HOST: ${{ secrets.EC2_HOST }}
    #   run:
    #     scp -i ~/.ssh/deploy_key delete_data.log $EC2_USER@$EC2_HOST:/home/ec2-user/simpleweb/logs/

    - name: Update MongoDB with JSON data
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
      run: |
        python -m pip install pymongo # 安裝pymongo
        python update_mongodb.py      # 執行更新腳本
    
    - name: Save log file to EC2
      env:
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
        scp -i ~/.ssh/deploy_key data_insertion.log $EC2_USER@$EC2_HOST:/home/ec2-user/simpleweb/logs/